// Generate golden_crux_corpus.js from melodies_decomposed.yaml
// Creates a Doh.Module with AVAILABLE_CRUX_PROGRAMS entries for each
// non-literal decomposition of each corpus melody.
//
// Usage: node crux/corpus/generate_crux_corpus.js

import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';
import YAML from 'yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const inputPath = path.join(__dirname, 'melodies_decomposed.yaml');
const outputPath = path.join(__dirname, '..', '..', 'modules', 'golden', 'golden_crux_corpus.js');

const raw = fs.readFileSync(inputPath, 'utf8');
const data = YAML.parse(raw);

const categoryToTag = {
    folk: 'tutorial',
    bach: 'baroque',
    classical: 'baroque',
    chant: 'baroque',
    edm: 'edm',
    minimalist: 'minimal',
};

const entries = [];

for (const melody of data.melodies) {
    const tag = categoryToTag[melody.category] || 'research';
    const nonLiteralDecomps = (melody.decompositions || []).filter(d => d.kind !== 'literal');

    // Count decompositions per kind to detect duplicates
    const kindCounts = {};
    for (const d of nonLiteralDecomps) {
        kindCounts[d.kind] = (kindCounts[d.kind] || 0) + 1;
    }
    const kindIndex = {};

    for (const decomp of nonLiteralDecomps) {
        // Strip directive comments from crux for the flattened display
        const flatCrux = melody.crux.split('\n').filter(l => !l.trim().startsWith('//')).join(' ').trim();
        // If decomposition uses a rhythm variable, show step-only literal + .j rhythm
        // so the comparison between flattened and compressed focuses on step structure.
        let commentCrux;
        if (decomp.code.includes('rhythm = ')) {
            // Strip timeScale suffixes (` | N` or ` | /N`) to show step-only version
            commentCrux = flatCrux.replace(/ \| \/?[0-9]+/g, '') + ' .j rhythm';
        } else {
            commentCrux = flatCrux;
        }
        const comment = `// ${melody.name} — flattened: ${commentCrux}`;
        const directives = [
            `// #pitchRegime ${melody.pitchRegime}`,
            `// #tonic ${melody.tonic % 12}`,
        ].join('\n');
        const program = `${comment}\n${directives}\n${decomp.code}`;

        let name;
        if (nonLiteralDecomps.length === 1) {
            name = melody.name;
        } else {
            // Track index within this kind for disambiguation
            kindIndex[decomp.kind] = (kindIndex[decomp.kind] || 0) + 1;
            if (kindCounts[decomp.kind] > 1) {
                name = `${melody.name} (${decomp.kind} #${kindIndex[decomp.kind]})`;
            } else {
                name = `${melody.name} (${decomp.kind})`;
            }
        }

        entries.push({
            name,
            description: `${melody.notes} [${melody.source}, ${melody.key}]`,
            tag,
            program,
        });
    }

    if (nonLiteralDecomps.length === 0) {
        console.log(`  SKIP ${melody.id} — no non-literal decompositions`);
    }
}

// Generate the JS module
const escapedEntries = entries.map(e => {
    const escapedProgram = e.program.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    return `        {
            name: ${JSON.stringify(e.name)},
            description: ${JSON.stringify(e.description)},
            tag: ${JSON.stringify(e.tag)},
            program: \`${escapedProgram}\`
        }`;
});

const output = `// AUTO-GENERATED by crux/corpus/generate_crux_corpus.js
// Do not edit manually. Re-run the script when melodies_decomposed.yaml changes.

Doh.Module('golden_crux_corpus', [
], function (golden = {globalThis:{}}) {

    const corpus_programs = [
${escapedEntries.join(',\n')}
    ];

    golden.AVAILABLE_CRUX_PROGRAMS = (golden.AVAILABLE_CRUX_PROGRAMS || []).concat(corpus_programs);
});
`;

fs.writeFileSync(outputPath, output, 'utf8');

console.log(`Generated ${entries.length} corpus program entries from ${data.melodies.length} melodies`);
console.log(`Output: ${outputPath}`);
