// Generate melodies_decomposed.yaml from melodies.yaml
// Runs each melody through the Crux decomposer and attaches results.

import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';
import YAML from 'yaml';
import '../src/index.js';
import '../src/decompose.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const inputPath = path.join(__dirname, 'melodies.yaml');
const outputPath = path.join(__dirname, 'melodies_decomposed.yaml');

const raw = fs.readFileSync(inputPath, 'utf8');
const data = YAML.parse(raw);

let totalDecompositions = 0;
let nonLiteralCount = 0;

for (const melody of data.melodies) {
  const result = golden.decompose(melody.crux);
  melody.decompositions = result.candidates.map(c => ({
    code: c.code,
    kind: c.kind,
    score: Math.round(c.score.total * 1000) / 1000,
  }));
  totalDecompositions += melody.decompositions.length;
  const hasNonLiteral = melody.decompositions.some(d => d.kind !== 'literal');
  if (hasNonLiteral) nonLiteralCount++;
  const best = melody.decompositions[0];
  const tag = best.kind !== 'literal' ? best.kind : 'literal only';
  console.log(`  ${melody.id.padEnd(25)} ${tag.padEnd(20)} ${melody.decompositions.length} candidates`);
}

const header = [
  '# Crux Test Corpus: Decomposition Results',
  '#',
  '# Generated by corpus/generate_decomposed.js',
  `# Date: ${new Date().toISOString().split('T')[0]}`,
  '#',
  '# Each melody entry includes a decompositions array with candidate Crux',
  '# programs discovered by the decomposer (Sprint 1: ranges, repeats, progressions).',
  '# Candidates are sorted by score (higher = more compression). The literal',
  '# baseline is always included as the last candidate.',
  '',
].join('\n');

const yamlStr = YAML.stringify(data, {
  lineWidth: 0,       // don't wrap lines
  singleQuote: false,
});

fs.writeFileSync(outputPath, header + yamlStr);

console.log(`\n${data.melodies.length} melodies processed`);
console.log(`${nonLiteralCount} with non-literal decompositions`);
console.log(`${totalDecompositions} total candidates`);
console.log(`Written to ${outputPath}`);
